ktpass -princ HTTP/fortigate.homelab.local@HOMELAB.LOCAL -mapuser fortigate -pass -crypto all -ptype KRB5_NT_PRINCIPAL -out fortigate.keytab



certutil -encode fortigate.keytab tmp.b64 && findstr /v /c:- tmp.b64 > fortigate.txt 
                OR 
certutil -encode fortigate.keytab fortigate.txt
